#!/bin/bash

help() {
  echo "Usage:"
  echo "  template create [type] [name]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  template::create "$@"
}

run() {
  core "$@"
}

run "$@"
