#!/bin/bash

template::install() {
  local name=$1

  if [ -z "$name" ]; then
    log::error "[$(timestamp)][template::install] name is required"
    return 1
  fi

  local template_url="${PLUGIN_TEMPLATE_REPO_PREFIX}${name}"
  local instance_path="$PLUGIN_PKGS/$name"

  log::debug "[$(timestamp)] name: $name"
  log::debug "[$(timestamp)] template_url: $template_url"
  log::debug "[$(timestamp)] instance_path: $instance_path"

  if [ -d "$instance_path" ]; then
    log::info "[$(timestamp)] template $name installed"
    return 
  fi

  if [ "$(net::is_not_found $template_url)" = "true" ]; then
    log::error "[$(timestamp)] template ($name) is not found"
    return 1
  fi

  git::clone $instance_path $template_url
  if [ "$?" != "0" ] || [ ! -d "$instance_path" ]; then
    log::error "[$(timestamp)] failed to install template $name."
    return 1
  fi

  log::success "[$(timestamp)] succeed to install template $name."
}

export -f template::install
